### ISSUE TITLE
Download Sequences link Isn't valid.

### ISSUE THREAD

**Issue by Chr0n0AP** [geohot/corona#43]
https://www.ncbi.nlm.nih.gov/core/assets/genbank/files/ncov-sequences.yaml gives a 404.

**Comment by tenexcoder** [comment]
Drop in replacement is https://www.dcc.fc.up.pt/~vsc/BIO/img/ncov-sequences.yaml 

As reference here is the updated link to the GenBank: https://www.ncbi.nlm.nih.gov/nuccore/MN908947

**Comment by Chr0n0AP** [comment]
Thank you for helping
