### ISSUE TITLE
Danish randomized study on facemasks

### ISSUE THREAD

**Issue by smurfd** [geohot/corona#48]
About 6000 participants

Study:
https://clinicaltrials.gov/ct2/show/NCT04337541?term=NCT04337541&draw=2&rank=1

Findings : 
https://www.acpjournals.org/doi/10.7326/M20-6817

Good? or too small? or not controlled enough?

**Comment by geohot** [comment]
I read the study before the results, was thinking this looks decent. This is definitely along the lines of the study I want, and will update my beliefs if there's a strong result!

But quoting the findings: "the difference observed was not statistically significant"

So any results could very well be noise, though at least it does seem to be preregistered (less chance for positive results bias). And considering its surgical masks, not cloth masks, I'm more inclined to believe some effect with that. 

If it's not noise, repeat it with a larger sample size, and it should be significant. For now, still keeping my belief in surgical masks <50%. In fact, that's what the study suggests. 46% chance helpful, 23% chance harmful.
